### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lubien** [projeto-spider/projeto-spider.github.io#1]
- [ ] Migrate current site to Nuxt.
  - [X] Make the current layout a Nuxt app (2016d37018873645317834edd73a6bc0ecbe825e).
  - [ ] Decouple data from templates.
- [ ] New layout.
- [x] Setup Travis CI builds.
  - [X] Build when push to `src` (204b491731f204a0a6897c46c469cebf7d0a5b67).
  - [x] Test build on PRs.
- [ ] Add contribution guidelines.
- [ ] Point spider.ufpa.br to this repo.
